### ISSUE TITLE
Bug - Controller Mapping

### ISSUE THREAD

**Issue by newuser9290** [zodttd/GammaSupportDocs#1]
Issues with controller mapping via backbone. Possibilty to set L3 or R3 as mappable for Menu button. Other users are reporting issues via DualShock or Xbox wireless controller as well with buttons resetting after gameplay. I do not experience this issue but mine is backbone and not connected via Bluetooth 

iPhone 13 Pro Max
iOS 18 (dev beta 1)
![image](https://github.com/zodttd/GammaSupportDocs/assets/164794137/e6197d6d-7c99-4d2a-9aaf-dc6ca023d73b)![image](https://github.com/zodttd/GammaSupportDocs/assets/164794137/e49957a5-377b-4167-be57-68ccb74cda5f)

**Comment by zodttd** [comment]
I’ll need to get a Bluetooth controller to test those again. Their button
mappings are reset after each game? I’ll get L3 and R3 mapped in the
next update. Thank you, much appreciated!

**Comment by zodttd** [comment]
I just released v1.5.4 that adds L3 R3 button mapping. It should be available in about an hour. It's a bit tricky to test mappings with all the devices so if you notice anything wrong with it, just let me know. I'll look into the bluetooth resetting issue next, as I still need to get a controller in-hand to test with.

**Comment by newuser9290** [comment]
Update 1.5.4 resolved issues with button remapping. Will reopen if bugs present with Bluetooth connectivity.
