### ISSUE TITLE
Bug… Screen Shot/“Select” normal function

### ISSUE THREAD

**Issue by IndigoSolJah** [zodttd/GammaSupportDocs#2]
Soul Reaver requires use of the “Select” button, also screen record is utilized by using the Select button. It was fine until I accidentally hit “Allow screen Record” now the “Select” button no longer performs its in game function.

**To Reproduce**
1. Open Soul Reaver and start gameplay
2. Hold “Select” button for a couple seconds
3. Hit “Allow Screen Record”
4. Now the “Select” button no longer functions

**Expected behavior**
“Select” button still operates as it would normally provided a single “quick press and release” of the “Select” button. Screen shot is a “double tap” and screen record is a “press and hold”. 

**Device Info**
 - OS: iOS
 - Version: iOS 17.5.1
- Device: iPhone 11

**Additional context**
Idk if this is context but I’d be cool if screenshot and screen record were in the drop down menu behind the “Menu” button where the “Disc Change” was recently added to totally free up the buttons I use during gameplay. Thanks for your time and consideration. Sick app btw. 

-IndigoSolJah

**Comment by zodttd** [comment]
Can you describe this issue a bit more? I know there's a Select gesture that prompts for screen recording. That gesture is currently disabled as people requested it be. Is this is the one you'd like enabled? If so I'll keep it in mind. I'll need to add some sort of screen recording option either way.
