### ISSUE TITLE
Silent Hill gameplay issues

### ISSUE THREAD

**Issue by newuser9290** [zodttd/GammaSupportDocs#4]
Apparently there are issues with silent hill gameplay with some users. Will be posting here to keep the GitHub active with any issues 

https://www.reddit.com/r/GammaEmulator/s/5yHD4iR3Yf

**Comment by newuser9290** [comment]
Closed as to not have multiple of the same issues opened

**Comment by zodttd** [comment]
Silent Hill (US region) is confirmed to be working in v1.6.1 and makes it
past this in-game save that people were reporting issues with. Precise
Cycles is set to Off, noting this as because setting can affect
compatibility.
