### ISSUE TITLE
Screen freeze after garage drefield Bug - Unexpected behavior in...

### ISSUE THREAD

**Issue by frederic-tenouh01** [zodttd/GammaSupportDocs#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, screenshots help a lot!

**Device Info**
 - OS: [e.g. iOS or iPadOS]
 - Version: [e.g. iOS 14.1]
- Device: [e.g. iPhone 12 Pro]

**Additional context**

**Comment by zodttd** [comment]
Hi!

It appears this bug report is missing information about which game this occurs in where the game freezes.


Regards,
ZodTTD

**Comment by zodttd** [comment]
Closed due to duplicate. Moving comments to original bug report.
